version: "2"
linters:
  settings:
    funlen:
      lines: 100
      statements: 40
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: false
    gocritic:
      enable-all: true
      disabled-checks:
        - ifElseChain
        - whyNoLint
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gocritic
    - goconst
    - gocyclo
    - rowserrcheck
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - sqlclosecheck
    - unconvert
    - whitespace

  exclusions:
    rules:
      - path: main.go
        linters:
          - gochecknoglobals
          - goconst
          - gocognit
          - gocritic
          - godox
          - revive
          - funlen
          - errcheck
          - gosec
      - path: (.+)_test.go
        linters:
          - gochecknoglobals
          - goconst
          - gocognit
          - gocritic
          - godox
          - revive
          - funlen
          - errcheck
          - gosec
          - gosimple
          - staticcheck
